"""
Habit and Sustainability models for long-term goal tracking.

Used by the Sustainability Agent for habit formation and pattern detection.
"""

from datetime import datetime
from enum import Enum
from typing import Optional

from sqlmodel import Field, SQLModel, Column
from sqlalchemy import JSON


class HabitStrength(str, Enum):
    """Strength of a habit."""
    FORMING = "forming"       # <21 days
    DEVELOPING = "developing" # 21-66 days
    ESTABLISHED = "established"  # 66-90 days
    AUTOMATIC = "automatic"   # >90 days


class InsightType(str, Enum):
    """Type of user insight."""
    PATTERN = "pattern"
    STRENGTH = "strength"
    WEAKNESS = "weakness"
    RECOMMENDATION = "recommendation"
    WARNING = "warning"


class HabitLoop(SQLModel, table=True):
    """
    Habit Loop model for tracking habit formation.
    
    Based on the Cue-Routine-Reward framework.
    """
    
    __tablename__ = "habit_loops"
    
    id: Optional[int] = Field(default=None, primary_key=True)
    user_id: int = Field(foreign_key="users.id", index=True)
    task_id: Optional[int] = Field(default=None, foreign_key="tasks.id", index=True)
    goal_id: Optional[int] = Field(default=None, foreign_key="goals.id", index=True)
    
    # Habit definition
    name: str = Field(max_length=255)
    description: Optional[str] = Field(default=None, max_length=1000)
    
    # Cue-Routine-Reward
    cue: str = Field(max_length=500)           # Trigger for the habit
    routine: str = Field(max_length=500)       # The behavior/action
    reward: str = Field(max_length=500)        # Immediate gratification
    
    # Tracking
    strength: HabitStrength = Field(default=HabitStrength.FORMING)
    days_tracked: int = Field(default=0)
    current_streak: int = Field(default=0)
    best_streak: int = Field(default=0)
    completion_rate: float = Field(default=0.0)
    
    # Time-based tracking
    target_time: Optional[str] = Field(default=None, max_length=50)  # e.g., "08:00"
    target_days: Optional[str] = Field(default=None, max_length=100)  # e.g., "Mon,Tue,Wed"
    
    # State
    is_active: bool = Field(default=True)
    last_performed_at: Optional[datetime] = Field(default=None)
    
    created_at: datetime = Field(default_factory=datetime.utcnow)
    updated_at: datetime = Field(default_factory=datetime.utcnow)
    
    class Config:
        """Pydantic config."""
        use_enum_values = True


class UserInsight(SQLModel, table=True):
    """
    User Insight model for storing pattern discoveries and recommendations.
    
    Generated by agents over time to improve personalization.
    """
    
    __tablename__ = "user_insights"
    
    id: Optional[int] = Field(default=None, primary_key=True)
    user_id: int = Field(foreign_key="users.id", index=True)
    goal_id: Optional[int] = Field(default=None, foreign_key="goals.id", index=True)
    
    # Insight details
    insight_type: InsightType = Field(default=InsightType.PATTERN)
    title: str = Field(max_length=255)
    description: str = Field(max_length=2000)
    
    # Source agent
    source_agent: str = Field(max_length=50)  # foundation, planning, execution, etc.
    
    # Importance and confidence
    importance: str = Field(default="medium", max_length=20)  # low, medium, high, critical
    confidence: float = Field(default=0.7, ge=0.0, le=1.0)
    
    # Action tracking
    is_actionable: bool = Field(default=False)
    action_taken: bool = Field(default=False)
    
    # JSON for flexible data
    data: Optional[dict] = Field(default=None, sa_column=Column(JSON))
    
    created_at: datetime = Field(default_factory=datetime.utcnow)
    expires_at: Optional[datetime] = Field(default=None)
    
    class Config:
        """Pydantic config."""
        use_enum_values = True


class DailyProgress(SQLModel, table=True):
    """
    Daily Progress model for tracking day-over-day activity.
    
    Used for pattern analysis and sustainability tracking.
    """
    
    __tablename__ = "daily_progress"
    
    id: Optional[int] = Field(default=None, primary_key=True)
    user_id: int = Field(foreign_key="users.id", index=True)
    goal_id: Optional[int] = Field(default=None, foreign_key="goals.id", index=True)
    
    # Date tracking (one entry per day per goal)
    date: datetime = Field(default_factory=datetime.utcnow)
    
    # Task metrics
    tasks_planned: int = Field(default=0)
    tasks_completed: int = Field(default=0)
    tasks_skipped: int = Field(default=0)
    completion_rate: float = Field(default=0.0)
    
    # Time metrics
    total_minutes_logged: int = Field(default=0)
    
    # Emotional state (if captured)
    mood_score: Optional[int] = Field(default=None, ge=1, le=10)
    energy_level: Optional[int] = Field(default=None, ge=1, le=10)
    
    # Notes
    notes: Optional[str] = Field(default=None, max_length=2000)
    
    created_at: datetime = Field(default_factory=datetime.utcnow)
    
    class Config:
        """Pydantic config."""
        use_enum_values = True
